import type { SpeciesContent } from './content';

// Swedish species card content (T-127). Claude first-pass translation of the English base
// (content.ts) for the Sweden alpha. Status: `machine` — **must be native-reviewed before
// shipping** (give/protect advice is correctness- and law-sensitive; INTERNATIONALIZATION.md,
// T-125). Same honesty rule as English: describe the season/behaviour, never claim real-time
// presence ("här just nu").

export const SV_CONTENT: Record<string, SpeciesContent> = {
  // Fåglar
  'common-swift': {
    speciesId: 'common-swift',
    fact: 'Tornseglare kan hålla sig i luften i flera månader i sträck och sover till och med under flykten.',
    whenAndHow: 'Under varma sommarkvällar, spana högt över hustaken och lyssna efter skrikande flockar.',
    give: 'Sätt upp en holk för tornseglare under takfoten innan fåglarna återvänder på våren.',
    protect: 'Vid renovering, bevara de små springorna under takfoten där tornseglare häckar.',
  },
  'barn-swallow': {
    speciesId: 'barn-swallow',
    fact: 'Ladusvalan flyttar ända till södra Afrika och tillbaka varje år.',
    whenAndHow: 'Från vår till tidig höst, håll utkik efter dem när de svävar lågt över öppna fält och vatten.',
    give: 'Lämna en lad- eller skjulsdörr på glänt så att de når sina boplatser.',
    protect: 'Undvik att riva gamla lerbon – svalor återanvänder dem år efter år.',
  },
  'common-cuckoo': {
    speciesId: 'common-cuckoo',
    fact: 'Göken lägger sina ägg i andra fåglars bon och uppfostrar aldrig sina egna ungar.',
    whenAndHow: 'På senvåren, lyssna efter det långväga ”ko-ko”-ropet från skogsbryn.',
    give: 'Stöd insektsrika ängar och häckar som föder de fåglar göken är beroende av.',
    protect: 'Håll dig till stigarna nära buskmark och vassar så att värdfåglarna inte störs.',
  },
  'european-robin': {
    speciesId: 'european-robin',
    fact: 'Rödhaken är hårt revirhävdande och kan sjunga natten igenom nära gatlyktor.',
    whenAndHow: 'Året runt i trädgårdar och skog; de följer ofta efter grävande arbete i hopp om maskar.',
    give: 'Lämna ett hörn av trädgården med löv där rödhaken kan söka föda.',
    protect: 'Skjut upp kraftig häckklippning tills häckningen är över på sensommaren.',
  },
  'common-blackbird': {
    speciesId: 'common-blackbird',
    fact: 'Hanens rika, flöjtande sång är en av de mest igenkännliga i Europa.',
    whenAndHow: 'Året runt; lyssna efter hanar som sjunger från tak och trädtoppar i gryning och skymning.',
    give: 'Ställ ut färskt vatten för dryck och bad, särskilt under torra perioder.',
    protect: 'Håll katter inomhus i gryningen under häckningssäsongen.',
  },
  fieldfare: {
    speciesId: 'fieldfare',
    fact: 'Björktrasten är en social trast som stryker omkring i högljudda, pratsamma vinterflockar.',
    whenAndHow: 'Under höst och vinter, se flockar rensa bär från häckar och rönnar.',
    give: 'Lämna bärbärande buskar som rönn och hagtorn oklippta över vintern.',
    protect: 'Låt fallfrukt ligga kvar på vintern – det är viktig föda i kylan.',
  },
  'great-tit': {
    speciesId: 'great-tit',
    fact: 'Talgoxar har ett stort läten-register och lär sig nya rop av sina grannar.',
    whenAndHow: 'Året runt; lyssna efter den ringande ”ti-ta, ti-ta”-sången från senvintern.',
    give: 'Sätt upp en holk med 32 mm hål på en lugn, skuggig plats.',
    protect: 'Undvik trädgårdsbekämpningsmedel så att det finns tillräckligt med larver till ungarna.',
  },
  'blue-tit': {
    speciesId: 'blue-tit',
    fact: 'En enda kull blåmesar kan äta över tusen larver.',
    whenAndHow: 'Året runt i trädgårdar och skog, ofta hängande upp och ner på tunna kvistar.',
    give: 'Sätt upp en liten holk med 25 mm hål i lä för rådande vind.',
    protect: 'Hoppa över insektsmedel på våren så att larver finns till ungarna.',
  },
  'common-chaffinch': {
    speciesId: 'common-chaffinch',
    fact: 'Bofinkens sång varierar mellan regioner, nästan som lokala dialekter.',
    whenAndHow: 'Vår till höst; hanar sjunger en ljus, fallande fras från öppna sittplatser.',
    give: 'Lämna en del fröställningar och ogräsfläckar stående under säsongen.',
    protect: 'Håll fågelmatningar rena för att hindra att sjukdomar sprids bland finkar.',
  },
  'eurasian-jay': {
    speciesId: 'eurasian-jay',
    fact: 'Nötskrikan gömmer tusentals ekollon varje höst och planterar hela ekskogar genom att glömma en del.',
    whenAndHow: 'Året runt i ekskog; håll utkik efter skymtar av rosa och blått på hösten.',
    give: 'Lämna fallna ekollon och löv under ekar orörda.',
    protect: 'Håll hundar på stigarna i skogen så att markfödande fåglar inte skräms upp.',
  },
  'great-spotted-woodpecker': {
    speciesId: 'great-spotted-woodpecker',
    fact: 'Dess vårtrummande är inte födosök utan en snabb trumvirvel för att hävda revir.',
    whenAndHow: 'Året runt; lyssna på senvintern efter trummande som ekar genom skogen.',
    give: 'Lämna stående död ved, som hyser de insekter hackspettar äter.',
    protect: 'Fäll inte döda eller döende träd som kan innehålla bohål.',
  },
  'white-wagtail': {
    speciesId: 'white-wagtail',
    fact: 'Ärlans ständiga stjärtviftande kan signalera vaksamhet mot rovdjur.',
    whenAndHow: 'Vår till höst nära vatten och öppen mark, springande och stannande för att fånga insekter.',
    give: 'Behåll en fläck kortklippt gräs eller grus nära vatten där de kan söka föda.',
    protect: 'Undvik att störa grus- och strandkanter där ärlor söker föda och häckar.',
  },
  'common-crane': {
    speciesId: 'common-crane',
    fact: 'Tranor utför hoppande, bugande speldanser tidigt på våren.',
    whenAndHow: 'Från vår till höst kring våtmarker; lyssna efter trumpetande rop som bär flera kilometer.',
    give: 'Stöd skyddet av odikade mossar och våta ängar där tranor häckar.',
    protect: 'Betrakta häckningsvåtmarker på avstånd – tranor överger störda bon.',
  },
  'whooper-swan': {
    speciesId: 'whooper-swan',
    fact: 'Sångsvanar parar sig för livet och annonserar ankomster med höga, trumpetande rop.',
    whenAndHow: 'Vår och höst på sjöar och översvämmade fält, ofta i familjegrupper.',
    give: 'Stöd att behålla grunda sjökanter och våta fält fria från dikning.',
    protect: 'Mata aldrig svanar med bröd – det skadar dem; håll avstånd på isen.',
  },
  mallard: {
    speciesId: 'mallard',
    fact: 'Ungarna kan simma och söka föda själva bara timmar efter kläckningen.',
    whenAndHow: 'Året runt på nästan vilken damm, sjö eller lugnt vattendrag som helst.',
    give: 'Om du matar änder, använd havre, ärtor eller frön i stället för bröd.',
    protect: 'Håll hundar borta från vattnet där änder häckar på våren.',
  },
  'common-buzzard': {
    speciesId: 'common-buzzard',
    fact: 'Ormvråken svävar på breda vingar och ropar ofta med ett kattlikt ”pi-ää”.',
    whenAndHow: 'Vår till höst; spana efter dem när de kretsar högt över fält och skogsbryn.',
    give: 'Stöd ängsmark och åkerkanter som hyser sorkar och smådjur.',
    protect: 'Använd aldrig råttgift, som vandrar upp i näringskedjan till rovfåglar.',
  },
  osprey: {
    speciesId: 'osprey',
    fact: 'Fiskgjusen dyker med fötterna först för att fånga fisk och kan bära byte som väger hälften av den själv.',
    whenAndHow: 'Vår till höst nära stora sjöar; håll utkik efter ryttling följt av ett dramatiskt dyk.',
    give: 'Stöd konstgjorda boplattformar på höga stolpar nära fiskrika sjöar.',
    protect: 'Ge boplattformar gott om utrymme så att paren inte skräms från äggen.',
  },

  // Däggdjur
  'red-fox': {
    speciesId: 'red-fox',
    fact: 'Rävar använder jordens magnetfält för att bedöma sina hopp mot dolt byte.',
    whenAndHow: 'Året runt, mest aktiv i gryning och skymning längs skogs- och åkerkanter.',
    give: 'Lämna ett vilt, ostört hörn där rävar kan vila och gräva lya.',
    protect: 'Säkra sopkärl och lämna aldrig skadliga matrester ute åt rävar.',
  },
  'european-hedgehog': {
    speciesId: 'european-hedgehog',
    fact: 'En igelkott kan färdas ett par kilometer under en enda natts födosök.',
    whenAndHow: 'Från vår till höst efter mörkrets inbrott; på vintern går de i ide under löv- och vedhögar.',
    give: 'Klipp ett 13 cm hål i staket så att igelkottar kan röra sig mellan trädgårdar.',
    protect: 'Kolla högt gräs innan du trimmar och lämna lövhögar för vinteride.',
  },
  'roe-deer': {
    speciesId: 'roe-deer',
    fact: 'Rådjur fördröjer sin dräktighet så att killingarna alltid föds på försommaren.',
    whenAndHow: 'Året runt i skogsbryn, mest synliga när de betar i gryning och skymning.',
    give: 'Stöd oklippta åkerkanter och buskmark som ger rådjur skydd och föda.',
    protect: 'Håll hundar kopplade nära skog på försommaren när killingar ligger gömda.',
  },
  moose: {
    speciesId: 'moose',
    fact: 'Älgen är världens största hjortdjur; en stor tjur kan väga över ett halvt ton.',
    whenAndHow: 'Året runt i skogar och våtmarker, mest aktiv i gryning och skymning.',
    give: 'Stöd sammanhängande skogar och våtmarkskorridorer som älgar behöver för att vandra.',
    protect: 'Kör försiktigt i gryning och skymning på skogsvägar och närma dig aldrig en kalv.',
  },
  'red-squirrel': {
    speciesId: 'red-squirrel',
    fact: 'Ekorren bygger flera bon, kallade risbon, och flyttar mellan dem.',
    whenAndHow: 'Året runt i barr- och blandskog, flitigast tidigt på morgonen.',
    give: 'Lämna kottar, nötter och stående träd som ekorrar äter och bor i.',
    protect: 'Håll hundar på stigarna och undvik att störa träd som kan hysa ett risbo.',
  },
  'european-beaver': {
    speciesId: 'european-beaver',
    fact: 'Bäverdammar skapar våtmarker som gynnar fisk, fåglar och insekter i milsvida områden.',
    whenAndHow: 'Från vår till sen höst kring lugna vattendrag, mest aktiv i skymningen.',
    give: 'Stöd att lämna bäverdammar och strandträd på plats där det är säkert.',
    protect: 'Håll avstånd från hyddor och dammar, särskilt när kuttingarna är små.',
  },
  'mountain-hare': {
    speciesId: 'mountain-hare',
    fact: 'Skogsharen blir vit på vintern för att smälta in mot snön.',
    whenAndHow: 'Året runt på öppen mark och skogsgläntor, främst i gryning och skymning.',
    give: 'Stöd en blandning av öppen mark och skydd som harar behöver året om.',
    protect: 'Håll hundar kopplade på öppen mark så att vilande harar inte jagas.',
  },
  'european-badger': {
    speciesId: 'european-badger',
    fact: 'Grävlingar lever i familjegrupper i underjordiska gryt som används i generationer.',
    whenAndHow: 'Från vår till höst efter mörkrets inbrott nära skog; de sover bort vintern.',
    give: 'Lämna ostörda slänter och häckar där grävlingar kan gräva gryt.',
    protect: 'Blockera eller gräv aldrig nära ett aktivt gryt – det är deras långvariga hem.',
  },
  'common-pipistrelle': {
    speciesId: 'common-pipistrelle',
    fact: 'Denna lilla fladdermus kan äta upp till 3 000 mygg på en natt.',
    whenAndHow: 'Sommarkvällar, håll utkik efter snabb, sicksackande flykt i skymningen över trädgårdar.',
    give: 'Sätt upp en fladdermusholk högt på en vägg eller ett träd som fångar kvällssolen.',
    protect: 'Undvik starkt ljus vid boplatser och håll natthimlen mörk för fladdermöss.',
  },

  // Insekter
  'small-tortoiseshell': {
    speciesId: 'small-tortoiseshell',
    fact: 'Denna fjäril övervintrar som vuxen, ofta i skjul och på vindar.',
    whenAndHow: 'Från tidig vår till höst på soliga blommor, särskilt nässlor och buddleja.',
    give: 'Lämna en fläck nässlor i ett soligt hörn – dess larver behöver dem.',
    protect: 'Lämna övervintrande fjärilar i fred i skjul över vintern.',
  },
  'european-peacock': {
    speciesId: 'european-peacock',
    fact: 'Ögonfläckarna blixtrar till för att skrämma fåglar, och vingarna kan väsa när de öppnas.',
    whenAndHow: 'Vår till höst under soliga dagar, på tistlar, buddleja och fallfrukt.',
    give: 'Låt en solig nässelfläck växa för dess larver.',
    protect: 'Stör inte vuxna fjärilar som söker skydd i skjul och vedhögar över vintern.',
  },
  'brimstone-butterfly': {
    speciesId: 'brimstone-butterfly',
    fact: 'Det engelska ordet ”butterfly” kan komma från citronfjärilshanens smörgula färg.',
    whenAndHow: 'En av vårens första fjärilar; spana längs skogsbryn under varma dagar.',
    give: 'Stöd brakvedsbuskar i häckar, de enda växter dess larver äter.',
    protect: 'Undvik att röja buskiga häckar som skyddar övervintrande vuxna.',
  },
  'orange-tip': {
    speciesId: 'orange-tip',
    fact: 'Bara hanarna har de klarorange vingspetsarna; honorna är vita.',
    whenAndHow: 'På våren längs fuktiga ängar och vägkanter där ängsbräsma växer.',
    give: 'Låt ängsbräsma och löktrav växa i fuktiga, oklippta hörn.',
    protect: 'Skjut upp klippning av vägkanter tills larverna ätit färdigt.',
  },
  'common-blue': {
    speciesId: 'common-blue',
    fact: 'Puktörneblåvingens larver sköts ibland av myror för deras söta utsöndringar.',
    whenAndHow: 'Från sen vår på soliga gräsmarker rika på klöver och käringtand.',
    give: 'Lämna gräsmark oklippt så att käringtand och klöver kan blomma.',
    protect: 'Undvik att spruta blomrika gräsmarker med ogräsmedel.',
  },
  'green-veined-white': {
    speciesId: 'green-veined-white',
    fact: 'Trots att den liknar en kålfjäril föredrar den vilda växter framför trädgårdsgrödor.',
    whenAndHow: 'Vår till sensommar på fuktiga ängar, diken och skogsstigar.',
    give: 'Låt fuktiga hörn växa vilt med inhemska korsblommiga växter som ängsbräsma.',
    protect: 'Undvik att dika ut och spruta fuktiga ängar där den förökar sig.',
  },
  'seven-spot-ladybird': {
    speciesId: 'seven-spot-ladybird',
    fact: 'En enda nyckelpiga kan äta tusentals bladlöss under sin livstid.',
    whenAndHow: 'Från vår till höst på växter med bladlöss; de samlas för att övervintra.',
    give: 'Tolerera en del bladlöss och hoppa över sprutning så att nyckelpigor har föda.',
    protect: 'Lämna ihåliga stjälkar och löv där nyckelpigor söker skydd över vintern.',
  },
  'buff-tailed-bumblebee': {
    speciesId: 'buff-tailed-bumblebee',
    fact: 'Drottningarna är bland de första bina ute på våren, surrande lågt för att hitta bohål.',
    whenAndHow: 'Från tidig vår till höst på blommor; drottningar söker häckbottnar på våren.',
    give: 'Odla eller lämna tidigblommande växter och låt klöver blomma i gräsmattan.',
    protect: 'Lämna ostörda slänter och gamla musgångar där kolonier bygger bo.',
  },
  'western-honey-bee': {
    speciesId: 'western-honey-bee',
    fact: 'Samlare talar om för kupan var blommor finns genom att dansa i en åtta.',
    whenAndHow: 'Från vår till höst på blommor under varma, stilla dagar.',
    give: 'Låt en mängd blommor blomma över säsongerna och ställ ut ett grunt vattenfat.',
    protect: 'Undvik att spruta blommande växter, och spruta aldrig mitt på dagen.',
  },
  'emperor-dragonfly': {
    speciesId: 'emperor-dragonfly',
    fact: 'En av Europas största trollsländor; den kan till och med fånga byte i luften.',
    whenAndHow: 'Under varma sommardagar, se den patrullera dammar och sjökanter.',
    give: 'Behåll eller gräv en damm med växter och lämna kanterna bevuxna.',
    protect: 'Håll dammar fria från föroreningar och avrinning så att larver kan utvecklas.',
  },
  'common-darter': {
    speciesId: 'common-darter',
    fact: 'Ängstrollsländor sitter ofta på samma varma plats och rusar ut för att fånga förbipasserande insekter.',
    whenAndHow: 'Från midsommar till höst nära stillastående vatten, solande på stigar och stolpar.',
    give: 'Lämna soliga sittplatser och växtlighet kring dammar och diken.',
    protect: 'Undvik att låta gödsel eller olja rinna ner i dammar där larver lever.',
  },
  'red-wood-ant': {
    speciesId: 'red-wood-ant',
    fact: 'Deras tuvbon kan vara över en meter höga och rymma en halv miljon myror.',
    whenAndHow: 'Från vår till höst i barrskog; leta efter kupolformade bon av barr.',
    give: 'Lämna myrstackar orörda – de tar år att bygga.',
    protect: 'Håll dig till stigarna och sparka eller gräv aldrig i en myrstack.',
  },

  // Växter
  'wood-anemone': {
    speciesId: 'wood-anemone',
    fact: 'Vitsippor sprider sig så långsamt att täta mattor tyder på gammal skog.',
    whenAndHow: 'På våren, leta efter mattor av vita blommor innan träden slår ut.',
    give: 'Lämna skogsbottnar ostörda så att de långsamt spridande rötterna kan trivas.',
    protect: 'Njut av dem där de växer – att plocka tar bort blommor som tagit år att sprida.',
  },
  'lily-of-the-valley': {
    speciesId: 'lily-of-the-valley',
    fact: 'Hela denna ljuvligt doftande växt är giftig om den äts.',
    whenAndHow: 'På senvåren, följ doften till skuggig skog och skuggiga trädgårdar.',
    give: 'Lämna skuggiga skogsbryn och löv där den växer.',
    protect: 'Plocka eller gräv inte upp den, och håll den borta från barn och husdjur.',
  },
  ramsons: {
    speciesId: 'ramsons',
    fact: 'Man känner ofta lukten av ramslök – vitlöksdoftande – innan man ser de vita blommorna.',
    whenAndHow: 'På våren, leta efter breda gröna blad och stjärnformade blommor i fuktig skog.',
    give: 'Lämna fuktig skog ostörd så att mattorna kan växa tillbaka varje år.',
    protect: 'Om plockning är tillåten lokalt, ta bara lite och dra aldrig upp lökarna.',
  },
  'marsh-marigold': {
    speciesId: 'marsh-marigold',
    fact: 'En av de äldsta inhemska växterna, den överlevde den senaste istiden i Skandinavien.',
    whenAndHow: 'På våren, leta efter stora gyllene blommor i kärr, diken och dammkanter.',
    give: 'Håll damm- och dikeskanter våta och oklippta så att den kan blomma.',
    protect: 'Undvik att dika ut våt mark och lämna växterna där de växer.',
  },
  cowslip: {
    speciesId: 'cowslip',
    fact: 'Gullvivor var förr så vanliga på slåtterängar att barn gjorde bollar av dem.',
    whenAndHow: 'På våren, leta efter nickande gula blommor på gamla, ogödslade ängar.',
    give: 'Lämna ängar oklippta tills gullvivorna blommat och satt frö.',
    protect: 'Plocka eller gräv inte upp dem från det vilda – ängsblommor minskar.',
  },
  'oxeye-daisy': {
    speciesId: 'oxeye-daisy',
    fact: 'Prästkragens blomma är egentligen dussintals små blommor tätt samlade.',
    whenAndHow: 'På sommaren, leta efter stora vita prästkragar längs vägkanter och ängar.',
    give: 'Lämna en remsa gräs oklippt över midsommar så att den kan blomma.',
    protect: 'Undvik att spruta vägkanter och ängar med ogräsmedel.',
  },
  'common-dandelion': {
    speciesId: 'common-dandelion',
    fact: 'Maskrosor är en av de viktigaste tidiga nektarkällorna för bin.',
    whenAndHow: 'Från våren nästan var som helst; blommorna öppnar sig i sol och sluter sig i skymningen.',
    give: 'Låt maskrosor blomma i gräsmattan på våren före första klippningen.',
    protect: 'Hoppa över gräsmatteogräsmedel så att tidiga pollinatörer behåller denna viktiga föda.',
  },
  heather: {
    speciesId: 'heather',
    fact: 'En enda ljungplanta kan producera över hundratusen små frön.',
    whenAndHow: 'På sensommaren, leta efter lila mattor på öppna hedar och myrar.',
    give: 'Stöd att hålla hedmark öppen och fri från dikning.',
    protect: 'Håll dig till stigarna på hedar och tänd aldrig eld i torka.',
  },
  bilberry: {
    speciesId: 'bilberry',
    fact: 'Blåbär färgar fingrarna blå och föder allt från fåglar till björnar.',
    whenAndHow: 'På sommaren, leta efter låga buskar med mörka bär i barrskog.',
    give: 'Lämna skogens undervegetation intakt så att de låga buskarna kan bära frukt.',
    protect: 'Om plockning är tillåten lokalt, lämna gott om bär åt djurlivet.',
  },
  lingonberry: {
    speciesId: 'lingonberry',
    fact: 'Lingon håller sig i månader tack vare ett naturligt konserveringsmedel i frukten.',
    whenAndHow: 'På sensommaren och hösten, leta efter blanka röda bär på städsegröna mattor.',
    give: 'Lämna skogsbottnens växtlighet ostörd så att mattorna kan sprida sig.',
    protect: 'Om plockning är tillåten lokalt, trampa försiktigt för att inte krossa växterna.',
  },
  'silver-birch': {
    speciesId: 'silver-birch',
    fact: 'En björk hyser hundratals insektsarter, som föder otaliga fåglar.',
    whenAndHow: 'Året runt; den vita, flagnande barken gör den lätt att känna igen i alla årstider.',
    give: 'Lämna fallna björklöv och död ved för att berika jorden och föda insekter.',
    protect: 'Undvik att skala bark, vilket kan såra och försvaga trädet.',
  },
  'norway-spruce': {
    speciesId: 'norway-spruce',
    fact: 'En gran i Sverige växer från rötter som är tusentals år gamla.',
    whenAndHow: 'Året runt i skogar; dess hängande kottar är de längsta av alla granar.',
    give: 'Lämna fallna kottar och död ved, som hyser insekter och svampar.',
    protect: 'Håll dig till stigarna i skogen för att inte packa granens ytliga rötter.',
  },
  'scots-pine': {
    speciesId: 'scots-pine',
    fact: 'Gamla tallar lyser orange högt upp och kan bli flera hundra år gamla.',
    whenAndHow: 'Året runt på sandig och stenig mark; leta efter den orange övre barken.',
    give: 'Lämna stående död ved och gamla tallar, som är rika på liv.',
    protect: 'Tänd aldrig eld mot eller nära tallar på torr, sandig mark.',
  },

  // Fisk
  'northern-pike': {
    speciesId: 'northern-pike',
    fact: 'Gäddan är ett bakhållsrovdjur som kan hugga ur stillhet på ett ögonblick.',
    whenAndHow: 'Från vår till höst i vassrika grunda områden i sjöar och lugna vattendrag.',
    give: 'Stöd att bevara vassrika grundområden och vattenväxter där ungfisk söker skydd.',
    protect: 'Håll föroreningar och skräp borta från vattnet; följ lokala fiskeregler.',
  },
  'european-perch': {
    speciesId: 'european-perch',
    fact: 'Abborrar jagar i stim och bär djärva ränder som bryter upp deras siluett.',
    whenAndHow: 'Under de varmare månaderna kring bryggor, vassbälten och branter.',
    give: 'Stöd rent vatten och undervattensstruktur som skyddar småfisk.',
    protect: 'Häll aldrig något i sjöar och vattendrag; följ lokala fiskeregler.',
  },
  roach: {
    speciesId: 'roach',
    fact: 'Mörten är en viktig bytesfisk som många rovdjur i sjön är beroende av.',
    whenAndHow: 'Under de varmare månaderna i stim nära ytan i sjöar och lugna vattendrag.',
    give: 'Stöd att hålla vattnet rent och kanterna bevuxna för lek.',
    protect: 'Håll avrinning och skräp borta från vattnet; följ lokala fiskeregler.',
  },
};
