// One-off generator: links the curated Kronoberg species to their real GBIF presence in Kronoberg
// (county SWE.9_1) and emits idempotent SQL — species.gbif_key/taxon_group/vertebrate + a
// species_presence row per matched species. Bounded (≤ the curated set) so it can be applied via
// the Supabase connector now, giving the alpha app real presence data while the full nationwide
// load runs through the pipeline (pipeline/gbif/supabase_load.py). Run: `npx tsx scripts/gen-kronoberg-presence.ts`.
import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { KRONOBERG_SPECIES } from '../lib/species/kronoberg';
import type { SpeciesCategory } from '../lib/species/types';

const KRONOBERG_GID = 'SWE.9_1';
const DATA_DIR = join(import.meta.dirname, '..', 'pipeline', 'data');

const VERTEBRATE: Record<SpeciesCategory, boolean> = {
  bird: true, mammal: true, fish: true, insect: false, plant: false, fungus: false,
};
const norm = (s: string) => s.trim().toLowerCase().split(/\s+/).slice(0, 2).join(' ');

// scientificName(normalized) → { speciesKey, activeMonths, occurrences } for Kronoberg.
const kron = new Map<string, { key: number; months: number[]; occ: number }>();
for (const file of readdirSync(DATA_DIR).filter((f) => f.startsWith('presence_') && f.endsWith('.json'))) {
  const doc = JSON.parse(readFileSync(join(DATA_DIR, file), 'utf8')) as {
    records: { county: string; speciesKey: number; scientificName: string; activeMonths: number[]; occurrences: number }[];
  };
  for (const r of doc.records) {
    if (r.county !== KRONOBERG_GID) continue;
    kron.set(norm(r.scientificName), { key: r.speciesKey, months: r.activeMonths, occ: r.occurrences });
  }
}

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const arr = (a: number[]) => `'{${a.join(',')}}'`;
const out: string[] = [
  '-- 0007 — link curated Kronoberg species to real GBIF presence (T-045, bounded seed).',
  '-- Generated by scripts/gen-kronoberg-presence.ts. Idempotent. Requires migration 0006.',
  'begin;',
  `insert into public.regions (id, name) values (${q(KRONOBERG_GID)}, 'Kronoberg') on conflict (id) do update set name=excluded.name;`,
];

let matched = 0;
const missing: string[] = [];
for (const s of KRONOBERG_SPECIES) {
  const hit = kron.get(norm(s.scientificName));
  if (!hit) { missing.push(s.id); continue; }
  matched++;
  out.push(
    `update public.species set gbif_key=${hit.key}, taxon_group=${q(s.category)}, vertebrate=${VERTEBRATE[s.category]} where id=${q(s.id)};`,
  );
  out.push(
    `insert into public.species_presence (region_id, species_id, active_months, occurrences) ` +
      `values (${q(KRONOBERG_GID)}, ${q(s.id)}, ${arr(hit.months)}, ${hit.occ}) ` +
      `on conflict (region_id, species_id) do update set active_months=excluded.active_months, occurrences=excluded.occurrences;`,
  );
}
out.push('commit;');

process.stderr.write(`matched ${matched}/${KRONOBERG_SPECIES.length} curated species in Kronoberg GBIF data\n`);
if (missing.length) process.stderr.write(`unmatched: ${missing.join(', ')}\n`);
process.stdout.write(out.join('\n') + '\n');
